### ISSUE TITLE
error: A problem occurred configuring project ':app_group_directory'.

### ISSUE THREAD

**Issue by Scalesse82** [istornz/flutter_live_activities#90] opened 2024-09-20 08:59 UTC
We are updating the project to Flutter 3.19.6. When building for Android, we are encountering the following issue on a library used by flutter_live_activities:

FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring project ':app_group_directory'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by Adrien-iAVC** [comment] 2024-10-04 09:51
Have the same problem here.

**Comment by istornz** [comment] 2024-10-18 14:09
Hello, thanks for raising an issue, I think the issue is now fixed with the new 2.0.0 version.
Can you check again ?

**Comment by istornz** [comment] 2024-11-27 14:37
I close the issue due to inactivity but feel free to reopen if the issue persist 👍

**Closed by istornz** 2024-11-27 14:37 UTC
